refactored unique class diff to new tool: dep_show_uniq

diff --git a/bin/dep_rm b/bin/dep_rm
--- a/bin/dep_rm
+++ b/bin/dep_rm
@@ -11,6 +11,11 @@ if [ $# -eq 0 ]; then
   exit 1
 fi
 
+if [ ! -d "${DEP_ROOTDIR}" ]; then
+  echo "Directory ${DEP_ROOTDIR} is missing"'!'" Run dep_init first"'!'
+  exit 1
+fi
+
 for eachClass in "$@"; do {
    if [ ! -f "${DEP_ROOTDIR}/${eachClass}" ]; then
       echo "Class ${eachClass} does not exist"'!'
@@ -18,15 +23,7 @@ for eachClass in "$@"; do {
    fi
 } done
 
-listOfClasses=$(mktemp)
-for eachClass in "$@"; do {
-  echo "$eachClass" >> "${listOfClasses}"
-} done
-
-# removed classes minus remaining classes
-grep -vFf <(find "${DEP_ROOTDIR}/" -type f | grep -vFf "${listOfClasses}" | xargs cat | awk '{print $3}' | sort -u) <(find "${DEP_ROOTDIR}/" -type f | grep -Ff "${listOfClasses}" | xargs cat | awk '{print $3}' | sort -u)
-
-rm "${listOfClasses}"
+dep_show_uniq "$@"
 
 for eachClass in "$@"; do {
    rm "${DEP_ROOTDIR}/${eachClass}"
